VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ThisWorkbook"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
'Upon opening Book1, hides Excel window and opens UserForm1

'Private Sub Workbook_Open()
    'Application.Visible = False
    'UserForm1.Show vbModeless
'End Sub

'Private Sub Workbook_Open()
'    UserForm1.Show vbModeless
'End Sub
